In [27]:
import pandas as pd

c = lambda f: 5 / 9 * (f - 32)

temps = [(f, c(f)) for f in range (0, 101, 10)]

import pandas as pd

temps_df = pd.DataFrame(temps, columns=['Fahrenheit', 'Celcius'])

axes = temps_df.plot(x='Fahrenheit', y='Celcius', style='.-')

y_label = axes.set_ylabel('Celcius')
    

In [28]:
 cd C:\Users\chris\Documents\44-608Fundamentals\IntroToPython\examples\ch15

C:\Users\chris\Documents\44-608Fundamentals\IntroToPython\examples\ch15


In [29]:
 nyc = pd.read_csv('ave_hi_nyc_jan_1895-2018.csv')

In [30]:
nyc.columns = ['Date', 'Temperature', 'Anomaly']

nyc.Date = nyc.Date.floordiv(100)

nyc.head(3)

Date  Temperature  Anomaly
0  1895         34.2     -3.2
1  1896         34.7     -2.7
2  1897         35.5     -1.9

In [31]:
%matplotlib

Using matplotlib backend: TkAgg


In [32]:
#Teaching our machine linear regression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(nyc.Date.values.reshape(-1, 1), nyc.Temperature.values, random_state=11)

X_train.shape

(93, 1)

In [33]:
X_test.shape

(31, 1)

In [34]:
from sklearn.linear_model import LinearRegression

In [35]:
linear_regression = LinearRegression()

linear_regression.fit(X=X_train, y=y_train)


LinearRegression()

In [36]:
#Finding the slope of the regression line
linear_regression.coef_


array([0.01939167])

In [37]:
#Finding the y-intercept of the regression line
linear_regression.intercept_

-0.30779820252656265

In [38]:
predicted = linear_regression.predict(X_test)

expected = y_test

for p, e in zip(predicted[::5], expected[::5]):
    print(f'predicted: {p:.2f}, expected{e:.2f}')

predicted: 37.86, expected31.70
predicted: 38.69, expected34.80
predicted: 37.00, expected39.40
predicted: 37.25, expected45.70
predicted: 38.05, expected32.30
predicted: 37.64, expected33.80
predicted: 36.94, expected39.70


In [39]:
predict = (lambda x: linear_regression.coef_ * x + linear_regression.intercept_)
#Making a prediction for 2019 based on the regression line
predict(2019)

array([38.84399018])

In [40]:
#Making a prediction for what is was in 1890 based on the regression line
predict(1890)

array([36.34246432])

In [41]:
#Making a scatterplot of the data
import seaborn as sns

axes = sns.scatterplot(data=nyc, x='Date', y='Temperature', hue='Temperature', palette='winter', legend=False)

In [42]:
axes.set_ylim(10, 70)

(10.0, 70.0)

In [43]:
import numpy as np

In [44]:
x = np.array([min(nyc.Date.values), max(nyc.Date.values)])

In [45]:
y = predict(x)

In [46]:
import matplotlib.pyplot as plt

line = plt.plot(x, y)

In [47]:
print('Chris Kollbaum')

Chris Kollbaum
